✨ add textarea
tonightpass/kitchen pull request #115
Opened 2023-01-16 13:31 UTC by YounesBessa

2023-01-20 00:21 UTC, AntoineKM requested changes
- [x] Disable `resize` capability
- [ ] Uses the same colors I used for the `Input` (#125)
- [ ] Define a color for the placeholder look at `Input` for an example

2023-01-20 00:21 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  height: 100px;
should be 100%

2023-01-20 00:21 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  width: 790px;
should be 100%

2023-01-20 00:21 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  height: 100px;
also add a min height ?

2023-01-20 00:21 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +      <Component
should be `<textarea`

2023-01-20 00:21 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +      ></Component>
should be a self closing tag

2023-01-20 20:34 UTC, jerembdn approved these changes

2023-01-26 14:18 UTC, AntoineKM requested changes

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  line-height: 1;
why ?

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  display: flex;
why ?

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  align-items: center;
why ?

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  justify-content: center;
why ?

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  padding: 7px 10px;
use `theme.gap`or padding i used for `Input`

2023-01-26 14:18 UTC, AntoineKM commented on packages/kitchen/src/components/Textarea/index.tsx
> +  width: 100%;
add width and height props so we can edit the width and height

2023-01-27 16:05 UTC, merged