📝 add avatar documentation
tonightpass/kitchen pull request #166
Opened 2023-02-28 13:10 UTC by YounesBessa

2023-02-28 16:53 UTC, jerembdn approved these changes

2023-03-02 18:25 UTC, AntoineKM requested changes

2023-03-02 18:25 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +<Container gap={5}>
gap={"small"}

2023-03-02 18:25 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +  <Container row align="center">
gap={"normal"}

2023-03-02 18:25 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +<Container gap={5}>
```
<Container gap={"small"} row>
    <Avatar text={"A"} />
    <Avatar text={"Joe"} />
    <Avatar text={"Jérémy Baudrin"} />
</Container>
```

2023-03-02 18:25 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +<Container gap={5}>
gap={"small"}

2023-03-02 18:25 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +| `size` | `number` \| `string` | `undefined` | - | The size of the avatar. | - |
default: 30

2023-03-03 13:41 UTC, AntoineKM requested changes

2023-03-03 13:41 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +  <Container row align="center" gap={"normal"}>
align={"center"}

2023-03-03 13:41 UTC, AntoineKM commented on docs/pages/docs/components/avatar.mdx
> +<Container gap={5}>
gap={"small"}

2023-03-03 13:48 UTC, AntoineKM approved these changes

2023-03-03 13:48 UTC, merged