📝 add image documentation
tonightpass/kitchen pull request #167
Opened 2023-02-28 15:38 UTC by YounesBessa

2023-02-28 16:28 UTC, jerembdn approved these changes

2023-03-02 18:27 UTC, AntoineKM requested changes

2023-03-02 18:27 UTC, AntoineKM commented on docs/pages/docs/components/image.mdx
> +    alt="Lorem picsum image"
alt={"Lorem picsum image"}

2023-03-02 20:22 UTC, AntoineKM approved these changes

2023-03-02 20:22 UTC, merged