📝 add error documentation
tonightpass/kitchen pull request #168
Opened 2023-02-28 16:46 UTC by YounesBessa

2023-02-28 17:00 UTC, jerembdn approved these changes

2023-03-02 18:35 UTC, AntoineKM requested changes
fix it:
inline-block:
![image](https://user-images.githubusercontent.com/54948363/222520538-dc4ddc58-07c2-4364-a43b-982614102826.png)

inline-flex:
![image](https://user-images.githubusercontent.com/54948363/222520641-fde5a3cc-15fc-42b7-93e3-413ca4ee6e2b.png)

2023-03-03 14:39 UTC, AntoineKM requested changes
All okay but add a changeset

2023-03-03 14:39 UTC, AntoineKM commented on docs/pages/docs/components/error.mdx
> +  <Error error={{ message: 'The request failed.', action: 'Contact Us', link: 'https://vercel.com/contact' }}/>
indent
```
<Error 
  error={{
    message: 'The request failed.',
    action: 'Contact Us',
    link: 'https://vercel.com/contact' 
  }}
/>
```

2023-03-03 15:07 UTC, AntoineKM commented
also use double quotes

2023-03-06 23:36 UTC, AntoineKM approved these changes

2023-03-06 23:36 UTC, merged