📝 add toggle documentation
tonightpass/kitchen pull request #173
Opened 2023-03-01 15:48 UTC by YounesBessa

2023-03-01 16:19 UTC, jerembdn approved these changes

2023-03-02 18:19 UTC, AntoineKM requested changes

2023-03-02 18:19 UTC, AntoineKM commented on docs/pages/docs/components/toggle.mdx
> +  const [checked1, toggle1] = useCheckbox(true);
this is second checked so replace `[checked1, toggle1]` by `[checked2, toggle2]`

2023-03-02 18:19 UTC, AntoineKM commented on docs/pages/docs/components/toggle.mdx
> +<Container gap={10}>
the indent is incorrect please fix it with tabulations

2023-03-02 18:19 UTC, AntoineKM commented on docs/pages/docs/components/toggle.mdx
> +  const [checked1, toggle1] = useCheckbox();
same here

2023-03-02 18:19 UTC, AntoineKM commented on docs/pages/docs/components/toggle.mdx
> +return (
ident error

2023-03-03 13:47 UTC, AntoineKM approved these changes

2023-03-03 13:47 UTC, merged