📝 add toast documentation
tonightpass/kitchen pull request #175
Opened 2023-03-03 15:15 UTC by YounesBessa

2023-03-03 15:20 UTC, jerembdn approved these changes

2023-03-03 15:23 UTC, AntoineKM requested changes

2023-03-03 15:23 UTC, AntoineKM commented on docs/pages/docs/components/toast.mdx
> +First of all, you need to import the `Toast` component from the `@tonightpass/kitchen` package.
importing toast comp isn't need but the useToats hook yep

2023-03-03 15:23 UTC, AntoineKM commented on docs/pages/docs/components/toast.mdx
> +  const { setToast } = useToasts();
add spaces between each part of code

2023-03-03 15:23 UTC, AntoineKM commented on docs/pages/docs/components/toast.mdx
> +  const alertAction = {
add spaces between each part of code

2023-03-03 15:23 UTC, AntoineKM commented on docs/pages/docs/components/toast.mdx
> +  const { setToast } = useToasts();
add spaces between each part of code

2023-03-07 16:14 UTC, AntoineKM approved these changes

2023-03-08 12:31 UTC, merged