✨ add checkbox
tonightpass/kitchen pull request #46
Opened 2022-11-17 17:34 UTC by YounesBessa

2022-11-19 22:17 UTC, AntoineKM requested changes
I don't know what these checkboxes are but the style will have to be completely revised, checkout #28.

2022-12-06 06:26 UTC, AntoineKM commented
@YounesBessa https://streamable.com/k2n7u3

2022-12-08 17:24 UTC, AntoineKM requested changes

2022-12-08 17:24 UTC, AntoineKM commented on examples/next-typescript/pages/checkbox.tsx
> +      <div
dont use ``div`` use ``Container`` instead

2022-12-08 17:24 UTC, AntoineKM commented on examples/next-typescript/pages/checkbox.tsx
> +          <Checkbox checked>Checked</Checkbox>
Why when you click on the checkbox it gets unchecked it should stay checked when it is true and unchecked when it is false
Reference: https://vercel.com/design/checkbox#checked

2022-12-08 17:24 UTC, AntoineKM commented on examples/next-typescript/pages/checkbox.tsx
> +          <Checkbox disabled>Disabled</Checkbox>
I don't see the substract icon

2022-12-08 17:24 UTC, AntoineKM commented on examples/next-typescript/pages/checkbox.tsx
> +          <Checkbox fullWidth>Full Width</Checkbox>
You have to test it in a ``Container`` with a ``maxWidth`` because it is impossible to test...

2022-12-08 17:24 UTC, AntoineKM commented on packages/kitchen/src/components/Checkbox/index.tsx
> +    const [checked, setChecked] = React.useState(checkedProp || value || false);
Shouldn't be here make a use checkbox hook like vercel please

2022-12-09 13:46 UTC, jerembdn requested changes

2022-12-09 13:46 UTC, jerembdn commented on packages/kitchen/src/components/Checkbox/index.tsx
> +
Spaces between lines are useless, remove them please

2022-12-09 13:46 UTC, jerembdn commented on packages/kitchen/src/components/Checkbox/index.tsx
> +    return (
Then here you can add a space between lines

2022-12-21 10:42 UTC, AntoineKM approved these changes

2022-12-21 13:32 UTC, merged